# https://docs.netlify.com/build/configure-builds/overview/#definitions
# We must set package="apps/storybook" in the UI
[build]
command = "pnpm -F @echonote/storybook build"
publish = "apps/storybook/storybook-static"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/storybook packages/tiptap packages/ui package.json pnpm-lock.yaml"

[build.environment]
NODE_VERSION = "22"
