# https://docs.netlify.com/build/configure-builds/overview/#definitions
# We must set package="apps/howto" in the UI
[build]
command = "pnpm -F @echonote/howto build"
publish = "apps/howto/dist"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/howto package.json pnpm-lock.yaml"

[build.environment]
NODE_VERSION = "22"
